print('Hello, World')
print('Hello, Again')
print('Hello,  This is fun')
print('Hello, yay Printingg')
print('Hello, something is better than nothing')
print('Hello, nothing is impossible')
print('now i will count my chickens')
print('hens',25+3/6)
print('roosters',100-25*3%4)
print('now i will \ncount the eggs')
print(3+2+1-5+4%2-1/4+6)
print('is it true that 3+2<5-7?')
print(3+2<5-7)
print('Hello, World',5>=-2)
print('Hello Praveen \t my qualification is \n BE CSE')
print('root---->node---->child')
print('root','child',sep='-->')
print('Hello, World',end=' ')
print('Hello, World')